{% set name = "click-spinner" %}
{% set version = "0.1.1" %}
{% set sha256 = "3fc5242797a1009cc40b2987709c8c75ab36b282cfb067a03e610495395243ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: 'file://{{ environ["RECIPE_DIR"] }}/README.md'
    sha256: 'ce6b86727ef77aa026826413de102e0076c773255698985b537792d49059219e'
    fn: README.md

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - click
    - pytest
  imports:
    - click_spinner
  files:
    - test_spinner.py
  commands:
    - py.test --pyargs test_spinner.py

about:
  home: https://github.com/click-contrib/click-spinner 
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Show that your command line app is active"
  description: |
    Sometimes you would just like to show the user some progress, but a 
    progress bar is not suitable because you don’t know how much longer it 
    would take. In these cases you might want to display a simple spinner 
    using the spinner() function.
  dev_url: https://github.com/click-contrib/click-spinner

extra:
  recipe-maintainers:
    - astamminger
