{% set name = "click-spinner" %}
{% set version = "0.1.4" %}
{% set sha256 = "045eaa50bdb3d9c0bf733ab0965077dbcb0873b3506634db8f9fbd67e58772ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: 'file://{{ environ["RECIPE_DIR"] }}/README.md'
    sha256: 'abe0f5f236791213b20a40aa6df3f61ff80c60e6572ae2b6ff52133c971284e3'
    fn: README.md

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - click
    - pytest
    - six
  imports:
    - click_spinner
  files:
    - test_spinner.py
  commands:
    - py.test --pyargs test_spinner.py

about:
  home: https://github.com/click-contrib/click-spinner 
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "Show that your command line app is active"
  description: |
    Sometimes you would just like to show the user some progress, but a 
    progress bar is not suitable because you don’t know how much longer it 
    would take. In these cases you might want to display a simple spinner 
    using the spinner() function.
  dev_url: https://github.com/click-contrib/click-spinner

extra:
  recipe-maintainers:
    - astamminger
