travis:
  secure:
    BINSTAR_TOKEN: D4h889eOiO7MumvWdmMrw6pNT8t9P5UanFB6Uq14iZYshzref+AeiVnBkklRNoageSO6UUR9iPW8EnL58el8tJlJq8agiTXS0UMjlQ+1VnjRwK0wamgIx1vBIMuxd5ZT2AdoYTcBX4EfMdZ6LBOTznhFKXHJK8STPFU0ZfpYrqquaPnomFjDA/VidXetHOxgYSEdBhjNWdXCkZxMEGQklwwn7w1wmB86bTTHZSPfSlL6EnSCsGvK0yDa0xZtjL+f/LmAbAvFPNuLClrYsyRYNlMm/hqcql+TtLpyH+fEYbnhfwt7h/1CAJGpRs+7mxHhA/hRA+MxdF+hp6ndB6wt3GiVkyQ8clYnFPVf1peLRocjdSXvFaqj9T1LgnEkU4VNA/9gkIcnWH1P4oBiXuPRcsr3wfvHAEJDziRKGsZBPCEgIzZeUtJkY2cP9Swmq//OlWOmu7QBw7QKHEyDf+nkDBPEyslkLzEwGKALvkLgIgjhVxZdZEJsBXrKCvw8sELp7Msa14fY0XTWDN6muyDvA3aNQXXsMfFoqYLdTNbwIXQ4QosQxHyEVcO8bLLy4dQ4EjKkXskX2nfps0Hg4BgyXU0b/ENR9el48eJCiXIikWIIyh7HKPf5WBL8uoLdIxhMxLsdReSBV5wx//hgYJNBwN12s2+7GnqVpLsGN8pD6EU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
